### ISSUE TITLE
Timestamp option?

### ISSUE THREAD

**Issue by svenha** [urbanware-org/salomon#51]
Is there a way to add a timestamp to each output element (or line)? A default would be to prepend a date and time in ISO 8601 format.

**Comment by urbanware-org** [comment]
> For example, if you have a log file from last month whose lines have no timestamps, I can't determine when those lines have been written into it.

Nevertheless, adding the last modification date of the log file would be possible.

**Comment by svenha** [comment]
I was thinking only about fresh lines that appear after the start of salomon. I have a set of logs that come form a complex system of several components. To understand the system it would be very helpful to see when which message appeared (roughly).

**Comment by urbanware-org** [comment]
Ah, now I see.

Yes, that should be possible. If nothing comes in between, I can add that the next few days.

**Comment by urbanware-org** [comment]
I just had some time to create a basic solution, see [this branch](https://github.com/urbanware-org/salomon/tree/feature/timestamp). However, this is an unfinished interim solution. If it works as you desire, I will revise the code and merge the finished one into the main branch.

The timestamp format can be set inside `salomon.cfg` via `leading_timestamp` at **line 153**.

In order to use that timestamp, simply add `--timestamp` as command-line argument.

Please let me know if this satisfies your needs.

**Comment by svenha** [comment]
Cool. That was quick.

I started testing ... looks good so far.

**Comment by urbanware-org** [comment]
Glad to help!

Alright, when you have tested everything you need, leave a note here as I will merge it then.

**Comment by svenha** [comment]
When salomon starts, the timestamps shown are not the ones from the mtime of the files, but the current time.

**Comment by urbanware-org** [comment]
Thanks for the feedback.

I just changed the code so the timestamp is the last modification time of the corresponding input file determined by `date -r`.

**Comment by svenha** [comment]
Works fine on several servers.
